# Generated by Django 4.2.9 on 2024-02-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
