# Generated by Django 4.2.9 on 2024-02-04 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebenezamanagement', '0010_delete_perforance_alter_teacher_subject'),
        ('Teacher', '0003_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('History', 'History'), ('English', 'English'), ('Maths', 'Maths'), ('Kiswahili', 'Kiswahili'), ('Science', 'Science')], max_length=150)),
                ('Marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebenezamanagement.student')),
            ],
        ),
    ]
