# Generated by Django 4.2.9 on 2024-02-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='Name',
            field=models.CharField(choices=[('Kiswahili', 'Kiswahili'), ('Science', 'Science'), ('Maths', 'Maths'), ('English', 'English'), ('History', 'History')], max_length=150),
        ),
    ]
