# Generated by Django 4.2.9 on 2024-02-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0005_alter_performance_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
