# Generated by Django 4.2.9 on 2024-02-02 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebenezamanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perforance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(choices=[('Kiswahili', 'Kiswahili'), ('Maths', 'Maths'), ('English', 'English'), ('Science', 'Science'), ('History', 'History')], max_length=150),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ProfilePic', models.ImageField(blank=True, null=True, upload_to='media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classteacher', models.BooleanField()),
                ('NationalID', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebenezamanagement.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParentProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebenezamanagement.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='Guardian',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ebenezamanagement.parent'),
            preserve_default=False,
        ),
    ]
