# Generated by Django 4.2.9 on 2024-02-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebenezamanagement', '0002_perforance_alter_subjects_name_userprofile_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='SchoolPic',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(choices=[('Kiswahili', 'Kiswahili'), ('Science', 'Science'), ('English', 'English'), ('History', 'History'), ('Maths', 'Maths')], max_length=150),
        ),
    ]
