# Generated by Django 4.2.9 on 2024-02-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebenezamanagement', '0004_alter_subjects_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='ParentProfile',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(choices=[('Science', 'Science'), ('English', 'English'), ('Kiswahili', 'Kiswahili'), ('History', 'History'), ('Maths', 'Maths')], max_length=150),
        ),
    ]
