# Generated by Django 4.2.9 on 2024-02-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebenezamanagement', '0006_alter_subjects_name_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('English', 'English'), ('Maths', 'Maths'), ('History', 'History'), ('Kiswahili', 'Kiswahili'), ('Science', 'Science')], max_length=150),
        ),
        migrations.DeleteModel(
            name='subjects',
        ),
    ]
