# Generated by Django 4.2.9 on 2024-02-04 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebenezamanagement', '0007_alter_teacher_subject_delete_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='user',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='Name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('History', 'History'), ('Science', 'Science'), ('Maths', 'Maths'), ('Kiswahili', 'Kiswahili'), ('English', 'English')], max_length=150),
        ),
    ]
