# Generated by Django 4.2.9 on 2024-02-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebenezamanagement', '0008_rename_user_parent_name_teacher_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('Kiswahili', 'Kiswahili'), ('Science', 'Science'), ('Maths', 'Maths'), ('History', 'History'), ('English', 'English')], max_length=150),
        ),
    ]
