# Generated by Django 4.2.9 on 2024-02-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebenezamanagement', '0009_student_admno_alter_teacher_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perforance',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('History', 'History'), ('English', 'English'), ('Maths', 'Maths'), ('Kiswahili', 'Kiswahili'), ('Science', 'Science')], max_length=150),
        ),
    ]
