# Generated by Django 4.2.9 on 2024-02-06 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebenezamanagement', '0011_alter_teacher_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=120)),
                ('Head', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Namme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebenezamanagement.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Grade', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='aboutvideo',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science'), ('English', 'English'), ('History', 'History'), ('Kiswahili', 'Kiswahili')], max_length=150),
        ),
    ]
