# Generated by Django 4.2.9 on 2024-02-06 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebenezamanagement', '0012_department_examination_subjects_delete_aboutvideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebenezamanagement.subjects'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('English', 'English'), ('History', 'History'), ('Maths', 'Maths'), ('Science', 'Science'), ('Kiswahili', 'Kiswahili')], max_length=150),
        ),
    ]
