# Generated by Django 4.2.9 on 2024-02-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebenezamanagement', '0013_alter_department_subject_alter_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='Grade',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=120),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('Science', 'Science'), ('Maths', 'Maths'), ('Kiswahili', 'Kiswahili'), ('English', 'English'), ('History', 'History')], max_length=150),
        ),
    ]
