# Generated by Django 4.2.9 on 2024-02-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebenezamanagement', '0014_alter_subjects_grade_alter_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='performance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebenezamanagement.subjects'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('History', 'History'), ('Science', 'Science'), ('Maths', 'Maths'), ('Kiswahili', 'Kiswahili'), ('English', 'English')], max_length=150),
        ),
    ]
