# Generated by Django 4.2.9 on 2024-02-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebenezamanagement', '0016_alter_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('Science', 'Science'), ('Maths', 'Maths'), ('English', 'English'), ('History', 'History'), ('Kiswahili', 'Kiswahili')], max_length=150),
        ),
    ]
